-- AlterTable
ALTER TABLE "client" ALTER COLUMN "number" SET DATA TYPE TEXT,
ALTER COLUMN "zipCode" SET DATA TYPE TEXT,
ALTER COLUMN "birthDate" SET DATA TYPE DATE,
ALTER COLUMN "registrationDate" SET DATA TYPE DATE;
